export const OPERATOR = {
    AMAZON: 'Amazon',
    ZEPTO: 'Zepto',
    FLIPKART:'Flipkart',
    SWIGGY: 'Swiggy',
    BIGBASKET: 'BigBasket',
}

export const PERFORMANCETABS = {
    OVERVIEW: 'OVERVIEW',
    PORTFOLIOS: 'PORTFOLIOS',
    CAMPAIGNS: 'CAMPAIGNS',
    ADGROUPS: 'ADGROUPS',
    KEYWORDS: 'KEYWORDS',
    PRODUCTS: 'PRODUCTS',
    PLACEMENTS: 'PLACEMENTS',
}

export const NEGATIVETABS = {
    SUGGESTED:"SUGGESTED",
    EXISTING:"EXISTING"
}